DROP TABLE vet_specialties PURGE;
DROP TABLE vets PURGE;
DROP TABLE specialties PURGE;
DROP TABLE visits PURGE;
DROP TABLE pets PURGE;
DROP TABLE types PURGE;
DROP TABLE owners PURGE;

CREATE TABLE vets (
  id         NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(255 CHAR),
  last_name  VARCHAR2(255 CHAR),
  PRIMARY KEY (id)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
  id   number(10,0) GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(255 CHAR),
  PRIMARY KEY (id)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
  vet_id       NUMBER(10,0) NOT NULL,
  specialty_id NUMBER(10,0) NOT NULL,
  PRIMARY KEY (vet_id, specialty_id)
);

CREATE TABLE types (
  id   NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR2(255 CHAR),
  PRIMARY KEY (id)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
  id         NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  first_name VARCHAR2(255 CHAR),
  last_name  VARCHAR2(255 CHAR),
  address    VARCHAR2(255 CHAR),
  city       VARCHAR2(255 CHAR),
  telephone  VARCHAR2(255 CHAR),
  PRIMARY KEY (id)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
  id         NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  name       varchar2(255 CHAR),
  birth_date DATE,
  type_id    NUMBER(10,0) NOT NULL,
  owner_id   NUMBER(10,0),
  PRIMARY KEY (id)
);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
  id          NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
  pet_id      NUMBER(10,0) NOT NULL,
  visit_date  DATE,
  description VARCHAR2(255 CHAR),
  PRIMARY KEY (id)
);
CREATE INDEX visits_pet_id ON visits (pet_id);

ALTER TABLE vet_specialties
  ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets(id);
ALTER TABLE vet_specialties
  ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties(id);
ALTER TABLE pets
  ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners(id);
ALTER TABLE pets
  ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types(id);
ALTER TABLE visits
  ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets(id);
